# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Michigan Tech\Concinnate Partners\Practice Code\PSGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PowerController
power = PowerController.power_control

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 336)
        self.vlimit = 0
        self.ilimit = 0

        self.device_V = QtWidgets.QLCDNumber(Dialog)
        self.device_V.setGeometry(QtCore.QRect(440, 60, 101, 41))
        self.device_V.setObjectName("device_V")
        self.Device_I = QtWidgets.QLCDNumber(Dialog)
        self.Device_I.setGeometry(QtCore.QRect(440, 110, 101, 41))
        self.Device_I.setObjectName("Device_I")
        self.voltage_dial = QtWidgets.QDial(Dialog)
        self.voltage_dial.setGeometry(QtCore.QRect(20, 20, 121, 101))
        self.voltage_dial.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.voltage_dial.setAcceptDrops(True)
        self.voltage_dial.setMaximum(40)
        self.voltage_dial.setSingleStep(1)
        self.voltage_dial.setWrapping(False)
        self.voltage_dial.setNotchesVisible(True)
        self.voltage_dial.setObjectName("voltage_dial")
        self.D_voltage = QtWidgets.QLCDNumber(Dialog)
        self.D_voltage.setGeometry(QtCore.QRect(30, 140, 101, 41))
        self.D_voltage.setSmallDecimalPoint(False)
        self.D_voltage.setObjectName("D_voltage")
        self.upload = QtWidgets.QPushButton(Dialog)
        self.upload.setGeometry(QtCore.QRect(110, 270, 101, 41))
        self.upload.setAutoFillBackground(False)
        self.upload.setAutoRepeat(False)
        self.upload.setObjectName("upload")
        self.current_dial = QtWidgets.QDial(Dialog)
        self.current_dial.setGeometry(QtCore.QRect(170, 20, 121, 101))
        self.current_dial.setMaximum(12)
        self.current_dial.setNotchesVisible(True)
        self.current_dial.setObjectName("current_dial")
        self.D_current = QtWidgets.QLCDNumber(Dialog)
        self.D_current.setGeometry(QtCore.QRect(180, 140, 101, 41))
        self.D_current.setObjectName("D_current")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(350, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(350, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(190, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 270, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.Reset = QtWidgets.QPushButton(Dialog)
        self.Reset.setGeometry(QtCore.QRect(580, 10, 101, 41))
        self.Reset.setAutoFillBackground(False)
        self.Reset.setAutoRepeat(False)
        self.Reset.setObjectName("Reset")
        self.vlim = QtWidgets.QSpinBox(Dialog)
        self.vlim.setGeometry(QtCore.QRect(350, 180, 101, 41))
        self.vlim.setObjectName("vlim")
        self.ilim = QtWidgets.QSpinBox(Dialog)
        self.ilim.setGeometry(QtCore.QRect(490, 180, 101, 41))
        self.ilim.setObjectName("ilim")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.voltage_dial.valueChanged.connect(self.voltage_sliderMoved)
        self.current_dial.valueChanged.connect(self.current_sliderMoved)

        self.vlim.valueChanged.connect(self.vlimits)
        self.ilim.valueChanged.connect(self.ilimits)

        self.Reset.clicked[bool].connect(power.reset)
        self.pushButton.clicked[bool].connect(power.set_VI_lim)
        self.upload.clicked[bool].connect(power.set_VI)
        self.upload.clicked[bool].connect(self.display)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.upload.setText(_translate("Dialog", "UPLOAD"))
        self.label.setText(_translate("Dialog", "Voltage"))
        self.label_2.setText(_translate("Dialog", "Current"))
        self.label_3.setText(_translate("Dialog", "Current Limit"))
        self.label_4.setText(_translate("Dialog", "Voltage Limit"))
        self.label_7.setText(_translate("Dialog", "Desired Voltage"))
        self.label_8.setText(_translate("Dialog", "Set Current"))
        self.pushButton.setText(_translate("Dialog", "Set Limits"))
        self.Reset.setText(_translate("Dialog", "RESET"))

    def voltage_sliderMoved(self):
        val = self.voltage_dial.value()
        self.D_voltage.display(val)
        power.getData_VD(val)

    def current_sliderMoved(self):
        val = self.current_dial.value()
        self.D_current.display(val)
        power.getData_ID(val)

    def vlimits(self):
        self.vlimit = self.vlim.value()
        power.getData_V(self.vlim.value())

    def ilimits(self):
        self.ilimit = self.ilim.value()
        power.getData_I(self.ilim.value())

    def display(self):
        V, I = power.read_VI()
       # I = (int)I
        #V = (int)V
        self.device_V.display(V)
        self.Device_I.display(I)


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
